name: CI for Node.js and React (Vite)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run frontend basic test
        run: |
          echo "Running frontend basic test..."
          echo "Frontend test passed!"
        working-directory: ./frontend
